# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
{{- if .Values.rbac.enabled -}}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "ditto.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ditto.name" . }}
{{ include "ditto.labels" . | indent 4 }}
rules:
- apiGroups:
    - "" # "" indicates the core API group
  resources:
    - "pods"
  verbs:
    - "get"
    - "watch"
    - "list"
    - "patch" # we require "patch" to annotate the pods with pod-deletion-cost
{{- end -}}
